name: Run Rust release workflow

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  rust-merge-flow:
    if: github.event.pull_request.merged == true
    name: Rust build debug and release builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
        BUILD_TARGET: [dev, release]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Rust project binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}
      - name: Set path for dev profile to debug
        id: upload-vars
        run: |
          if [[ "${{ matrix.BUILD_TARGET }}" == "dev" ]]; then
            echo "artifact_path_name=target/debug" >> $GITHUB_OUTPUT
          else
            echo "artifact_path_name=target/${{ matrix.BUILD_TARGET }}" >> $GITHUB_OUTPUT
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-binaries-${{ matrix.BUILD_TARGET }}
          path: ${{ steps.upload-vars.outputs.artifact_path_name }}/discord-bridge-rs
          retention-days: 2
